# Generated by Django 5.1.7 on 2025-06-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0002_alter_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='level',
            field=models.IntegerField(),
        ),
    ]
